// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.UI.WebControls;

namespace Connect.Modules.UserManagement.AccountUpdate
{
    public partial class Settings
    {

        /// <summary>
        /// lblUsernameMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblUsernameMode;

        /// <summary>
        /// drpUsernameMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpUsernameMode;

        /// <summary>
        /// lblDisplaynameMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblDisplaynameMode;

        /// <summary>
        /// drpDisplaynameMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpDisplaynameMode;

        /// <summary>
        /// lblRedirectAfterSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblRedirectAfterSubmit;

        /// <summary>
        /// drpRedirectAfterSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpRedirectAfterSubmit;

        /// <summary>
        /// lblUsermanagementTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblUsermanagementTab;

        /// <summary>
        /// drpUserManagementTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpUserManagementTab;

        /// <summary>
        /// lblAddToRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAddToRole;

        /// <summary>
        /// drpAddToRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpAddToRole;

        /// <summary>
        /// lblAddToRoleStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAddToRoleStatus;

        /// <summary>
        /// drpRoleStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpRoleStatus;

        /// <summary>
        /// lblRemoveFromRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblRemoveFromRole;

        /// <summary>
        /// drpRemoveFromRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpRemoveFromRole;

        /// <summary>
        /// lblNotifyRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblNotifyRole;

        /// <summary>
        /// drpNotifyRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpNotifyRole;

        /// <summary>
        /// lblNotifyUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblNotifyUser;

        /// <summary>
        /// chkNotifyUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkNotifyUser;

        /// <summary>
        /// lblInterface control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblInterface;

        /// <summary>
        /// txtInterface control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtInterface;

        /// <summary>
        /// lblCompareFirstNameLastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblCompareFirstNameLastName;

        /// <summary>
        /// chkCompareFirstNameLastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkCompareFirstNameLastName;

        /// <summary>
        /// lblValidateEmailThroughRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblValidateEmailThroughRegex;

        /// <summary>
        /// chkValidateEmailThroughRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkValidateEmailThroughRegex;

        /// <summary>
        /// lblEmailRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblEmailRegex;

        /// <summary>
        /// txtEmailRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtEmailRegex;
    }
}