// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace Connect.Modules.UserManagement.AccountUpdate
{
    public partial class Templates
    {

        /// <summary>
        /// plTheme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl plTheme;

        /// <summary>
        /// drpThemes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList _drpThemes;

        protected DropDownList drpThemes
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _drpThemes;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_drpThemes != null)
                {
                    _drpThemes.SelectedIndexChanged -= drpThemes_SelectedIndexChanged;
                }

                _drpThemes = value;
                if (_drpThemes != null)
                {
                    _drpThemes.SelectedIndexChanged += drpThemes_SelectedIndexChanged;
                }
            }
        }

        /// <summary>
        /// cmdCopySelected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdCopySelected;

        protected LinkButton cmdCopySelected
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdCopySelected;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdCopySelected != null)
                {
                    _cmdCopySelected.Click -= cmdCopySelected_Click;
                }

                _cmdCopySelected = value;
                if (_cmdCopySelected != null)
                {
                    _cmdCopySelected.Click += cmdCopySelected_Click;
                }
            }
        }

        /// <summary>
        /// cmdDeleteSelected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdDeleteSelected;

        protected LinkButton cmdDeleteSelected
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdDeleteSelected;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdDeleteSelected != null)
                {
                    _cmdDeleteSelected.Click -= cmdDeleteSelected_Click;
                }

                _cmdDeleteSelected = value;
                if (_cmdDeleteSelected != null)
                {
                    _cmdDeleteSelected.Click += cmdDeleteSelected_Click;
                }
            }
        }

        /// <summary>
        /// pnlLocales control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl pnlLocales;

        /// <summary>
        /// plLocale control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl plLocale;

        /// <summary>
        /// drpLocales control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList _drpLocales;

        protected DropDownList drpLocales
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _drpLocales;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_drpLocales != null)
                {
                    _drpLocales.SelectedIndexChanged -= drpLocales_SelectedIndexChanged;
                }

                _drpLocales = value;
                if (_drpLocales != null)
                {
                    _drpLocales.SelectedIndexChanged += drpLocales_SelectedIndexChanged;
                }
            }
        }

        /// <summary>
        /// plUseTheme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl plUseTheme;

        /// <summary>
        /// chkUseTheme control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkUseTheme;

        /// <summary>
        /// pnlTemplateName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl pnlTemplateName;

        /// <summary>
        /// plTemplateName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl plTemplateName;

        /// <summary>
        /// txtTemplateName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtTemplateName;

        /// <summary>
        /// AccountUpdateTemplatesTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl AccountUpdateTemplatesTabs;

        /// <summary>
        /// lblFormTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblFormTemplate;

        /// <summary>
        /// lblEmailUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblEmailUser;

        /// <summary>
        /// lblEmailAdmin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblEmailAdmin;

        /// <summary>
        /// txtFormTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtFormTemplate;

        /// <summary>
        /// txtEmailUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtEmailUser;

        /// <summary>
        /// txtEmailAdmin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtEmailAdmin;

        /// <summary>
        /// cmdUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdUpdate;

        protected LinkButton cmdUpdate
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdUpdate;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdUpdate != null)
                {
                    _cmdUpdate.Click -= cmdUpdate_Click;
                }

                _cmdUpdate = value;
                if (_cmdUpdate != null)
                {
                    _cmdUpdate.Click += cmdUpdate_Click;
                }
            }
        }

        /// <summary>
        /// cmdUpdateExit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdUpdateExit;

        protected LinkButton cmdUpdateExit
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdUpdateExit;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdUpdateExit != null)
                {
                    _cmdUpdateExit.Click -= cmdUpdateExit_Click;
                }

                _cmdUpdateExit = value;
                if (_cmdUpdateExit != null)
                {
                    _cmdUpdateExit.Click += cmdUpdateExit_Click;
                }
            }
        }

        /// <summary>
        /// cmdCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdCancel;

        protected LinkButton cmdCancel
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdCancel;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdCancel != null)
                {
                    _cmdCancel.Click -= cmdCancel_Click;
                }

                _cmdCancel = value;
                if (_cmdCancel != null)
                {
                    _cmdCancel.Click += cmdCancel_Click;
                }
            }
        }
    }
}